name: Deploy the infrastructure

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'infra/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::356700923537:role/resume-challenge-terraform
          aws-region: eu-central-1

      - name: Setup aws cli
        uses: unfor19/install-aws-cli-action@master
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve 

      - name: Copy all files to s3
        run: aws s3 sync ./frontend s3://uriel-resume-challenge
        shell: bash

      # - name: Create an invalidation on cloudfront
      #   shell: bash
      #   run: |
      #     # Output contains the cloudfront distribution id
      #     terraform output > output
      #     aws s3 sync . 