name: Deploy the infrastructure

on:
  push:
    branches: [main]
    paths:
      - 'frontend/resume.html'
      - 'infra/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::356700923537:role/resume-challenge-terraform
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve 
